"use client";

import { Calculator, RotateCcw, TriangleAlert } from "lucide-react";
import { useState, type FormEvent } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { calculateBeam, calculateStripFoundation, type BeamInput, type BeamResult, type StripFoundationInput, type StripFoundationResult } from "@/features/calculators/preliminary-calculations";

export type CalculatorKind = "beam" | "strip-foundation";
type StringValues<T> = { [K in keyof T]: string };

const initialBeam: StringValues<BeamInput> = { spanM: "6", loadKnPerM: "10", widthMm: "300", heightMm: "500", modulusGpa: "30", allowableDeflectionRatio: "250" };
const initialFoundation: StringValues<StripFoundationInput> = { lengthM: "10", widthM: "0.5", heightM: "0.6", verticalLoadKn: "600", soilResistanceKpa: "150" };

function parseValues<T extends object>(values: StringValues<T>): T { return Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) as T; }
function number(value: number, fractionDigits = 2) { return new Intl.NumberFormat("ru-RU", { maximumFractionDigits: fractionDigits }).format(value); }

function NumberField({ label, value, unit, onChange }: { label: string; value: string; unit: string; onChange: (value: string) => void }) {
  return <label className="block text-sm font-medium text-slate-800">{label}<span className="mt-1.5 flex overflow-hidden rounded-lg border border-slate-300 bg-white focus-within:ring-2 focus-within:ring-blue-600"><input aria-label={label} type="number" min="0" step="any" value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 flex-1 px-3 py-2 outline-none" /><span className="flex items-center border-l border-slate-200 bg-slate-50 px-3 text-xs text-slate-600">{unit}</span></span></label>;
}

function ResultRow({ label, value }: { label: string; value: string }) { return <div className="flex items-baseline justify-between gap-4 border-b border-slate-100 py-2 last:border-0"><dt className="text-sm text-slate-600">{label}</dt><dd className="text-right text-sm font-semibold text-slate-950">{value}</dd></div>; }
function Condition({ met, children }: { met: boolean; children: React.ReactNode }) { return <p role="status" className={met ? "rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-950" : "rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm font-medium text-amber-950"}>{met ? "Условие по введённому критерию выполнено. " : "Условие по введённому критерию не выполнено. "}{children}</p>; }

function BeamScheme({ values }: { values: StringValues<BeamInput> }) {
  return <figure aria-label="Расчётная схема балки" className="rounded-xl border border-blue-100 bg-blue-50/60 p-4"><figcaption className="text-sm font-semibold text-slate-900">Расчётная схема</figcaption><div className="relative mx-auto mt-6 h-36 max-w-lg px-7"><span className="absolute left-7 right-7 top-12 border-t-4 border-slate-800" /><span className="absolute left-7 top-[52px] size-0 border-x-[14px] border-t-[20px] border-x-transparent border-t-blue-700" /><span className="absolute right-7 top-[52px] size-0 border-x-[14px] border-t-[20px] border-x-transparent border-t-blue-700" /><span className="absolute left-10 right-10 top-0 flex justify-around text-blue-700">↓ ↓ ↓ ↓ ↓</span><span className="absolute left-1/2 top-[-2px] -translate-x-1/2 text-xs font-semibold text-blue-800">q = {values.loadKnPerM || "—"} кН/м</span><span className="absolute bottom-1 left-7 right-7 border-t border-slate-500" /><span className="absolute bottom-3 left-1/2 -translate-x-1/2 bg-blue-50 px-2 text-xs font-semibold text-slate-700">L = {values.spanM || "—"} м</span></div><div className="mt-2 flex justify-center gap-4 text-xs text-slate-700"><span>Сечение b × h: {values.widthMm || "—"} × {values.heightMm || "—"} мм</span><span>E: {values.modulusGpa || "—"} ГПа</span></div></figure>;
}

function FoundationScheme({ values }: { values: StringValues<StripFoundationInput> }) {
  return <figure aria-label="Расчётная схема ленточного фундамента" className="rounded-xl border border-amber-100 bg-amber-50/60 p-4"><figcaption className="text-sm font-semibold text-slate-900">Расчётная схема</figcaption><div className="relative mx-auto mt-5 h-36 max-w-lg"><span className="absolute left-1/2 top-0 -translate-x-1/2 text-sm font-semibold text-slate-800">N = {values.verticalLoadKn || "—"} кН ↓</span><span className="absolute left-1/2 top-7 h-9 border-l-4 border-slate-700" /><span className="absolute left-[18%] right-[18%] top-16 h-9 rounded-sm border-2 border-slate-700 bg-slate-300" /><span className="absolute left-[9%] right-[9%] top-[105px] border-t-4 border-amber-700" /><span className="absolute bottom-0 left-1/2 -translate-x-1/2 text-xs font-semibold text-slate-700">B = {values.widthM || "—"} м · h = {values.heightM || "—"} м</span></div><div className="mt-2 flex justify-center gap-4 text-xs text-slate-700"><span>ΣL: {values.lengthM || "—"} м</span><span>R: {values.soilResistanceKpa || "—"} кПа</span></div></figure>;
}

export function CalculatorsWorkspace({ kind }: { kind: CalculatorKind }) {
  const isBeam = kind === "beam";
  const [beam, setBeam] = useState(initialBeam);
  const [foundation, setFoundation] = useState(initialFoundation);
  const [beamResult, setBeamResult] = useState<BeamResult | null>(null);
  const [foundationResult, setFoundationResult] = useState<StripFoundationResult | null>(null);
  const [error, setError] = useState("");
  const updateBeam = <K extends keyof BeamInput,>(key: K, value: string) => { setBeam((current) => ({ ...current, [key]: value })); setBeamResult(null); setError(""); };
  const updateFoundation = <K extends keyof StripFoundationInput,>(key: K, value: string) => { setFoundation((current) => ({ ...current, [key]: value })); setFoundationResult(null); setError(""); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (isBeam) { const result = calculateBeam(parseValues<BeamInput>(beam)); if (result.ok) { setBeamResult(result.data); setError(""); } else setError(result.error); } else { const result = calculateStripFoundation(parseValues<StripFoundationInput>(foundation)); if (result.ok) { setFoundationResult(result.data); setError(""); } else setError(result.error); } };
  const reset = () => { setError(""); if (isBeam) { setBeam(initialBeam); setBeamResult(null); } else { setFoundation(initialFoundation); setFoundationResult(null); } };
  const result = isBeam ? beamResult : foundationResult;

  return <div className="mx-auto max-w-5xl"><section className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Badge variant="secondary">Предварительная проверка</Badge><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{isBeam ? "Балка на двух опорах" : "Давление ленточного фундамента"}</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">{isBeam ? "Шарнирно-опёртая балка с равномерно распределённой нагрузкой по всему пролёту." : "Равномерное центральное вертикальное нагружение подошвы без моментов."}</p></div><div className="flex max-w-md gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-5 text-amber-950"><TriangleAlert className="mt-0.5 size-5 shrink-0" />Результат не является проектным решением или заключением о безопасности конструкции.</div></section>
    <Card className="mt-8"><CardContent className="grid gap-8 p-5 sm:p-6 lg:grid-cols-[minmax(0,1fr)_minmax(300px,0.85fr)]"><form onSubmit={submit} noValidate><div className="grid gap-4 sm:grid-cols-2">{isBeam ? <><NumberField label="Пролёт L" value={beam.spanM} unit="м" onChange={(value) => updateBeam("spanM", value)} /><NumberField label="Нагрузка q" value={beam.loadKnPerM} unit="кН/м" onChange={(value) => updateBeam("loadKnPerM", value)} /><NumberField label="Ширина сечения b" value={beam.widthMm} unit="мм" onChange={(value) => updateBeam("widthMm", value)} /><NumberField label="Высота сечения h" value={beam.heightMm} unit="мм" onChange={(value) => updateBeam("heightMm", value)} /><NumberField label="Модуль упругости E" value={beam.modulusGpa} unit="ГПа" onChange={(value) => updateBeam("modulusGpa", value)} /><NumberField label="Допустимый прогиб L/n" value={beam.allowableDeflectionRatio} unit="n" onChange={(value) => updateBeam("allowableDeflectionRatio", value)} /></> : <><NumberField label="Суммарная длина L" value={foundation.lengthM} unit="м" onChange={(value) => updateFoundation("lengthM", value)} /><NumberField label="Ширина подошвы B" value={foundation.widthM} unit="м" onChange={(value) => updateFoundation("widthM", value)} /><NumberField label="Высота ленты h" value={foundation.heightM} unit="м" onChange={(value) => updateFoundation("heightM", value)} /><NumberField label="Вертикальная нагрузка N" value={foundation.verticalLoadKn} unit="кН" onChange={(value) => updateFoundation("verticalLoadKn", value)} /><NumberField label="Сопротивление грунта R" value={foundation.soilResistanceKpa} unit="кПа" onChange={(value) => updateFoundation("soilResistanceKpa", value)} /></>}</div>{error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}<div className="mt-5 flex flex-wrap gap-3"><Button type="submit"><Calculator className="size-4" />Рассчитать</Button><Button type="button" variant="outline" onClick={reset}><RotateCcw className="size-4" />Сбросить</Button></div></form>{isBeam ? <BeamScheme values={beam} /> : <FoundationScheme values={foundation} />}</CardContent></Card>
    {result ? <Card className="mt-8"><CardHeader><CardTitle>Результат</CardTitle></CardHeader><CardContent><dl>{isBeam && beamResult ? <><ResultRow label="Реакция каждой опоры" value={`${number(beamResult.supportReactionKn)} кН`} /><ResultRow label="Макс. поперечная сила" value={`${number(beamResult.maxShearKn)} кН`} /><ResultRow label="Макс. изгибающий момент" value={`${number(beamResult.maxMomentKnM)} кН·м`} /><ResultRow label="Момент инерции I" value={`${number(beamResult.inertiaMm4, 0)} мм⁴`} /><ResultRow label="Расчётный / допустимый прогиб" value={`${number(beamResult.deflectionMm)} / ${number(beamResult.allowableDeflectionMm)} мм`} /></> : foundationResult ? <><ResultRow label="Площадь подошвы" value={`${number(foundationResult.footingAreaM2)} м²`} /><ResultRow label="Среднее давление p" value={`${number(foundationResult.contactPressureKpa)} кПа`} /><ResultRow label="Предельная нагрузка Nmax" value={`${number(foundationResult.maxLoadKn)} кН`} /><ResultRow label="Использование p/R" value={number(foundationResult.utilizationRatio, 3)} /><ResultRow label="Запас / превышение" value={`${number(foundationResult.reserveKn)} кН`} /><ResultRow label="Объём бетона" value={`${number(foundationResult.concreteVolumeM3)} м³`} /></> : null}</dl><div className="mt-4"><Condition met={isBeam ? beamResult!.deflectionConditionMet : foundationResult!.pressureConditionMet}>{isBeam ? "Проверка выполнена только по введённому ограничению прогиба." : "Сравнение выполнено с введённым сопротивлением грунта."}</Condition></div></CardContent></Card> : null}
    <details className="mt-8 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-700"><summary className="cursor-pointer font-semibold text-slate-900">Формулы и ограничения</summary>{isBeam ? <><p className="mt-2">R = Vmax = qL/2; Mmax = qL²/8; I = bh³/12; f = 5qL⁴/(384EI).</p><p className="mt-2">Включите собственный вес и нужные сочетания в q. Проверка не учитывает прочность, трещины, устойчивость, опирание и армирование.</p></> : <><p className="mt-2">A = L×B; p = N/A; Nmax = R×A; V = L×B×h.</p><p className="mt-2">Включите собственный вес фундамента в N. Не учитываются эксцентриситет, осадка, слои грунта, воды, морозное пучение, сейсмика и армирование.</p></>}</details>
  </div>;
}
